create table if not exists public.quiz_games (
  code text primary key check (code ~ '^[A-Z2-9]{5}$'),
  status text not null default 'lobby' check (status in ('lobby','playing','finished')),
  current_round integer not null default 0 check (current_round between 0 and 8),
  round_started_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_players (
  id uuid primary key default gen_random_uuid(),
  game_code text not null references public.quiz_games(code) on delete cascade,
  name text not null check (char_length(name) between 1 and 32),
  created_at timestamptz not null default now()
);
create index if not exists quiz_players_game_idx on public.quiz_players(game_code);

create table if not exists public.quiz_answers (
  id bigint generated by default as identity primary key,
  game_code text not null references public.quiz_games(code) on delete cascade,
  player_id uuid not null references public.quiz_players(id) on delete cascade,
  round integer not null check (round between 1 and 8),
  answer text not null check (char_length(answer) between 2 and 80),
  correct boolean not null,
  response_ms integer not null check (response_ms between 0 and 30000),
  created_at timestamptz not null default now(),
  unique (player_id, round)
);
create index if not exists quiz_answers_game_round_idx on public.quiz_answers(game_code, round);

create table if not exists public.student_clips (
  id uuid primary key default gen_random_uuid(),
  display_name text not null default 'Anonym stemme' check (char_length(display_name) between 1 and 32),
  dialect text not null check (char_length(dialect) between 1 and 80),
  prompt text not null check (char_length(prompt) between 10 and 240),
  audio_path text not null unique,
  public_url text not null,
  consented boolean not null check (consented),
  consent_version text not null default 'event-v1',
  consented_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.clip_guesses (
  id bigint generated by default as identity primary key,
  clip_id uuid not null references public.student_clips(id) on delete cascade,
  guess text not null check (char_length(guess) between 1 and 80),
  created_at timestamptz not null default now()
);

alter table public.quiz_games enable row level security;
alter table public.quiz_players enable row level security;
alter table public.quiz_answers enable row level security;
alter table public.student_clips enable row level security;
alter table public.clip_guesses enable row level security;

grant usage on schema public to anon;
grant select, insert, update on public.quiz_games to anon;
grant select, insert on public.quiz_players to anon;
grant select, insert on public.quiz_answers to anon;
grant select, insert on public.student_clips to anon;
grant insert on public.clip_guesses to anon;
grant usage, select on all sequences in schema public to anon;

create policy "event games can be read" on public.quiz_games for select to anon using (created_at > now() - interval '24 hours');
create policy "event games can be created" on public.quiz_games for insert to anon with check (status = 'lobby' and current_round = 0);
create policy "event games can advance" on public.quiz_games for update to anon using (created_at > now() - interval '24 hours') with check (created_at > now() - interval '24 hours');
create policy "event players can be read" on public.quiz_players for select to anon using (created_at > now() - interval '24 hours');
create policy "event players can join" on public.quiz_players for insert to anon with check (created_at > now() - interval '5 minutes');
create policy "event answers can be read" on public.quiz_answers for select to anon using (created_at > now() - interval '24 hours');
create policy "event answers can be submitted" on public.quiz_answers for insert to anon with check (created_at > now() - interval '5 minutes');
create policy "consented clips can be heard" on public.student_clips for select to anon using (consented and created_at > now() - interval '7 days');
create policy "consented clips can be added" on public.student_clips for insert to anon with check (consented and consent_version = 'event-v1' and created_at > now() - interval '5 minutes');
create policy "clip guesses can be added" on public.clip_guesses for insert to anon with check (created_at > now() - interval '5 minutes');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('dialect-clips', 'dialect-clips', true, 8000000, array['audio/webm','audio/mp4','audio/ogg','audio/wav','audio/mpeg'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "event audio can be uploaded" on storage.objects for insert to anon with check (
  bucket_id = 'dialect-clips'
  and lower(storage.extension(name)) = any (array['webm','mp4','ogg','wav','mp3'])
);
