drop policy if exists "student guesses can be added" on public.student_guesses;
drop policy if exists "event audio is readable" on storage.objects;

create table if not exists public.clip_guesses (
  id bigint generated by default as identity primary key,
  clip_id uuid not null references public.student_clips(id) on delete cascade,
  guess text not null check (char_length(guess) between 1 and 80),
  created_at timestamptz not null default now()
);
create index if not exists clip_guesses_clip_idx on public.clip_guesses(clip_id);
alter table public.clip_guesses enable row level security;
grant insert on public.clip_guesses to anon;
grant usage, select on all sequences in schema public to anon;
create policy "clip guesses can be added" on public.clip_guesses for insert to anon with check (created_at > now() - interval '5 minutes');
